import React from "react";
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";

pdfMake.vfs = pdfFonts.pdfMake.vfs;

const PdfGenerator = ({
  companyName = "My Company Pvt Ltd",
  logo,
  tableHeaders = [],
  tableData = [],
  footerText = "Generated by My Company ERP",
  fileName = "report.pdf",
}) => {
  const generatePDF = () => {
    const docDefinition = {
      pageMargins: [40, 80, 40, 60],
      header: {
        margin: [40, 20],
        columns: [
          logo
            ? {
                image: logo,
                width: 60,
              }
            : {},
          {
            text: companyName,
            style: "header",
            alignment: "center",
          },
        ],
      },
      footer: (currentPage, pageCount) => ({
        text: `${footerText} | Page ${currentPage} of ${pageCount}`,
        alignment: "center",
        fontSize: 9,
        margin: [0, 10],
      }),
      content: [
        {
          table: {
            headerRows: 1,
            widths: Array(tableHeaders.length).fill("*"),
            body: [
              tableHeaders.map((h) => ({ text: h, style: "tableHeader" })),
              ...tableData.map((row) => row.map((cell) => ({ text: cell }))),
            ],
          },
          layout: "lightHorizontalLines",
        },
      ],
      styles: {
        header: {
          fontSize: 16,
          bold: true,
          margin: [0, 10],
        },
        tableHeader: {
          bold: true,
          fillColor: "#e5e5e5",
        },
      },
    };

    pdfMake.createPdf(docDefinition).download(fileName);
  };

  return (
    <button onClick={generatePDF} className="btn btn-primary">
      Download PDF
    </button>
  );
};

export default PdfGenerator;
